# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test_openai',
                'doc_host': 'https://Pankajkumar-Bankar.github.io',
                'git_url': 'https://github.com/Pankajkumar-Bankar/test_openai',
                'lib_path': 'test_openai'},
  'syms': {'test_openai.core': {'test_openai.core.foo': ('core.html#foo', 'test_openai/core.py')}}}
